---
layout: cv
title: Zachary Swart's Resume
---
# Zachary Swart

<div id="webaddress">
<a href="mailto:swa21007@byui.edu">swa21007@byui.edu</a>
| <a href="https://www.linkedin.com/in/zacharyswart">www.linkedin.com/in/zacharyswart</a>
</div>

## My Education

**B.S. in Business Analytics – Full Time**  
Brigham Young University - Idaho, Rexburg, ID  
*Jan 2024 – Jan 2028*  
- Overall GPA: 3.93  
- Relevant Courses: Databases (SQL), Spreadsheet Analysis (Excel), & Business Analytics (Power BI).  
- BYU-Idaho Academic Scholarship

**Colony High School**  
*2017 – 2021*

## Work Experience

**SQL Teaching Assistant – Part Time**  
Brigham Young University – Idaho, Rexburg, ID  
*Apr 2025 – Present*  
- Provides database querying, data manipulation, and analysis techniques through hands-on support and tutoring.  
- Instructed 15+ students in SQL through in-class sessions, covering key topics such as JOINs, REGEXPs, CASE statements, window functions, aggregate functions, and subqueries.  
- Redesigned 4 exams to better align with course objectives and emphasize real-world SQL application scenarios.

**Career Success Mentor – Part Time**  
Brigham Young University – Idaho, Rexburg, ID  
*Jan 2025 – Present*  
- Provides career support services, resume reviews, and job search assistance to thousands of students worldwide.  
- Achieved 98.1% average customer satisfaction rating in post-appointment surveys.  
- Mentored 150+ students by leading individualized mentorship sessions and tailoring support strategies for internship and job goals.

**Polaris – Intern**  
Polaris Inc., Rexburg, ID  
*Apr 2024 – Aug 2024*  
- Global leader in powersports, known for innovation and performance.  
- Improved station time efficiency by 16% using Lean Six Sigma principles.  
- Maintained 140–160 unit daily production with 99.5% on-time attendance, supporting team performance.

## Leadership

**Volunteer Representative**  
Church of Jesus Christ of Latter-day Saints, Colorado Springs, CO  
*Oct 2021 – Oct 2023*  
- Supported 200+ individuals through personalized lessons and service.  
- Led weekly council meetings for teams of 5+, promoting collaboration and goal achievement.

## Projects

**Excel Data Tracker**  
*Apr 2025 – May 2025*  
- Boosted data validation speed by 400% using automated Excel tools with VBA and macros to detect appointment entry errors.

**BYU-Idaho Hackathon**  
*Nov 2024*  
- Built functional SQL relational database in a team of 4 for a time management web app using HTML, CSS, and JavaScript during a 24-hour coding challenge.

## Key Skills

Excel | MySQL | Power BI | Python | R | PowerPoint | Word | Office & Outlook | HTML | CSS
